// ─── Theme Data ───────────────────────────────────────────────────────────────
const THEMES = {

  // ── Nature & Places ──────────────────────────────────────────────────────────

  animals: {
    words: [
      'BEAR','BIRD','BUCK','COLT','CRAB','CROW','DEER','DOVE','DUCK','FAWN',
      'FROG','HAWK','HARE','IBIS','KITE','LAMB','LYNX','MOLE','MOTH','MULE',
      'NEWT','PONY','TOAD','VOLE','WREN','BISON','CRANE','DINGO','EAGLE','GECKO',
      'HERON','KOALA','LEMUR','OTTER','PANDA','QUAIL','RAVEN','SNAKE','STORK','STOAT','VIXEN',
      'BADGER','MAGPIE','OSPREY','RABBIT','SALMON','THRUSH','WEASEL','BEAVER','FERRET'
    ],
    hidden: [
      { word: 'WILD',   story: "\"Tell me, what is it you plan to do with your one wild and precious life?\" — Mary Oliver, The Summer Day" },
      { word: 'FERAL',  story: "In the 1980s, a population of domestic rabbits was released on Macquarie Island near Antarctica. Within decades they had stripped the island nearly bare, destabilizing cliffs and destroying seabird colonies. Removing them took twenty years and cost $25 million. Domesticity, it turns out, is no guarantee of harmlessness." },
      { word: 'FAUNA',  story: "The word comes from Fauna, a Roman goddess of earth and fertility — sister to Faunus, god of the forest. Carl Linnaeus borrowed her name in 1745 to mean \"the animals of a place.\" Every field guide in the world is quietly dedicated to a forgotten goddess." },
      { word: 'PROWL',  story: "A lioness named Scarlett's Sister in the Maasai Mara was documented making solo kills for over a decade — unusual for lions, who hunt in groups. Rangers tracked her movements for years. She never once hunted the same corridor twice in a row." },
      { word: 'ROOST',  story: "A murmuration of starlings can contain over a million birds moving as a single fluid shape. No leader directs them — each bird tracks its seven nearest neighbors. The math that governs them is the same math that governs school fish and beating hearts." },
      { word: 'GRAZE',  story: "A single cow grazing a field does not eat randomly — it moves in consistent patterns, favoring certain grasses, avoiding others, returning to the same patches in the same order. Ecologists call this \"selective grazing.\" The field that looks uniform to us is a deeply familiar landscape to them." },
      { word: 'STALK',  story: "\"The hunter crouches in his blind / 'til dusk and danger pass. / The outcome of his long pursuit / belongs to God and grass.\" — Ogden Nash, The Hunter" },
      { word: 'HAUNT',  story: "A solitary sperm whale known as 52 Hertz has been tracked by Navy hydrophones since 1989. It calls at a frequency no other whale uses — too high for them to hear. It has been singing into silence for over thirty years. Whether it is lonely is a question we cannot answer. That we keep asking it says something about us." },
      { word: 'BURROW', story: "Wombats produce cube-shaped droppings — the only known animal to do so. They use them to mark territory on rocks and logs without them rolling away. Scientists spent years studying the digestive mechanics. The secret is in the last 8% of the intestine, where the walls pulse unevenly." },
      { word: 'FORAGE', story: "In 2009, a crow named 007 at a Japanese university was filmed using a sequence of eight tools in the correct order to retrieve food — planning multiple steps ahead. He hadn't been taught the sequence. He figured it out alone, over several days of quiet observation." }
    ]
  },

  beach: {
    words: [
      'BASK','BUOY','CLAM','COVE','CRAB','DUNE','FOAM','GULL','KELP','PIER',
      'REEF','SAIL','SAND','SURF','TIDE','WAKE','WAVE','ZINC','BEACH','CLIFF',
      'COAST','CONCH','CORAL','DRIFT','FLOAT','FROTH','INLET','JETTY','ROCKS','SHELL',
      'SHOAL','SHORE','SPRAY','SWELL','TIDAL','TOWEL','ANCHOR','BIKINI','BREEZE','BUCKET',
      'DINGHY','LAGOON','LIMPET','MUSSEL','PEBBLE','RIPPLE','SANDAL','SHRIMP','SPLASH','SUNTAN',
      'URCHIN','WHELKS'
    ],
    hidden: [
      { word: 'BRINE',  story: "The ocean is about 3.5 percent salt — but that ratio varies. The Dead Sea is nearly ten times saltier, dense enough that human bodies float without effort. The word salary comes from the Latin sal, because Roman soldiers were sometimes paid in salt or given an allowance to buy it. Salt has been currency, preservative, and medicine for most of human history. At the cellular level, it is still what we are made of." },
      { word: 'ATOLL',  story: "Charles Darwin proposed his theory of coral atoll formation in 1842 — nearly two decades before On the Origin of Species, and long before any technology existed to verify it. He argued that atolls were reefs growing upward around slowly sinking volcanic islands, leaving only the ring when the island finally disappeared. In 1952, a drill on Eniwetok Atoll struck volcanic basalt 1,400 meters below the coral. Darwin was right." },
      { word: 'HAVEN',  story: "\"The cure for anything is salt water: sweat, tears, or the sea.\" — Isak Dinesen, Seven Gothic Tales, 1934. Dinesen was the pen name of Karen Blixen, a Danish writer who ran a coffee farm in Kenya for seventeen years. She wrote the line in the middle of financial ruin, a failed marriage, and the beginning of exile. It has since appeared on refrigerator magnets, tattoos, and sympathy cards worldwide — almost always without attribution." },
      { word: 'SPUME',  story: "The foam at the edge of a breaking wave is called spume. It forms when dissolved organic matter — algae, fish scales, the proteins of a billion tiny organisms — gets churned into bubbles by the wave's collapse. It is the sea's own lather, its evidence of life made briefly visible. On a calm day it collects in drifts at the tide line. It lasts about ten seconds before the water pulls it back." },
      { word: 'NEAP',   story: "Twice a month, when the sun, moon, and Earth form a right angle rather than a straight line, the tides grow smaller — neither fully pulling nor fully pushing. These are neap tides. The name comes from an Old English word meaning scanty, lacking. Spring tides — the large ones at new and full moon — arrive in all four seasons. The word comes not from the season but from the Old English springan: to leap." },
      { word: 'GYRE',   story: "The North Pacific Subtropical Gyre is a slow clockwise current the size of a continent, driven by wind and the rotation of the Earth. At its center, where currents converge and debris accumulates, lies the Great Pacific Garbage Patch — roughly 79,000 metric tons of plastic spread across an area twice the size of Texas. It is not a solid island. It is a diffuse soup, mostly invisible from the surface. The gyre has been collecting it since the 1950s." },
      { word: 'SWASH',  story: "The sheet of water that surges up the beach after a wave breaks is called swash. The water that flows back down is backwash. The line where swash stops and reverses — where the sand is darkest, where the shells concentrate, where children dare each other to stand — is the swash limit. Coastal engineers study it carefully. Most beachgoers discover it instinctively, usually by misjudging it once." },
      { word: 'ERODE',  story: "The Yorkshire coast has been retreating for two thousand years. The Romans built a garrison town on the headland; it is under the North Sea now. The cliffs there erode at roughly half a meter per year — slow enough that no one notices season to season, fast enough that thirty villages have disappeared since the Normans arrived. Their names still appear in medieval tax records. The land beneath them is gone." },
      { word: 'FLEET',  story: "In August 1588, the Spanish Armada — 130 ships, 18,000 soldiers, the most powerful naval force in the world — sailed for England and was destroyed not by the English navy but by weather. English ships harassed them up the Channel; Atlantic gales finished the job. Fewer than 70 of the 130 ships returned to Spain. Queen Elizabeth I had medals struck with a Latin inscription: Flavit Jehovah et Dissipati Sunt. God blew, and they were scattered." },
      { word: 'SIREN',  story: "In Greek mythology, the Sirens were not mermaids — they were women with the bodies of birds. The mermaid version appeared gradually through the Middle Ages, merging with separate fish-woman traditions from Babylonian and Celtic mythology. By the Renaissance the bird form was almost entirely forgotten. Homer never described what they looked like at all. He only described the singing, and what it did to men who heard it." }
    ]
  },

  space: {
    words: [
      'AXIS','DARK','DAWN','DUST','FLUX','HALO','HAZE','LOOP','MASS','MOON',
      'NOVA','RING','VOID','WAVE','ZONE','COMET','FLARE','ORBIT','PHASE','PROBE',
      'PULSE','QUARK','REALM','SOLAR','SPARK','DEBRIS','HELIUM','IMPACT','ZENITH','PHOTON',
      'NEBULA','METEOR','PULSAR','CORONA','AURORA','QUASAR'
    ],
    hidden: [
      { word: 'VAST',    story: "\"Space is big. You just won't believe how vastly, hugely, mind-bogglingly big it is.\" — Douglas Adams, The Hitchhiker's Guide to the Galaxy" },
      { word: 'DRIFT',   story: "Objects left in low Earth orbit don't stay there forever — atmospheric drag slowly pulls them down. But objects left in higher orbits will remain for millions of years. The Voyager 1 probe, launched in 1977, is now over 23 billion kilometers away and still sending data. It will drift through interstellar space long after every human alive today is gone." },
      { word: 'ABYSS',   story: "The Boötes Void is a region of space roughly 330 million light-years across containing almost nothing — no galaxies, no stars, no known matter. It is so empty that astronomers initially assumed their instruments were broken. Its existence is not fully explained by any current model of the universe." },
      { word: 'COSMIC',  story: "\"The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself.\" — Carl Sagan, Cosmos" },
      { word: 'LAUNCH',  story: "\"Earth is the cradle of humanity, but one cannot remain in the cradle forever.\" — Konstantin Tsiolkovsky, pioneer of astronautics, written in 1895 — 58 years before the first satellite launch" },
      { word: 'STELLAR', story: "In 1054 AD, astronomers in China, Japan, and the Arab world all independently recorded a new star so bright it was visible in daylight for 23 days. No European record exists — historians believe the Church considered it theologically inconvenient. What they saw was a supernova. Its remnant, the Crab Nebula, is still expanding today at 1,500 kilometers per second." },
      { word: 'HORIZON', story: "When Apollo 8 astronaut William Anders looked back at Earth from lunar orbit on Christmas Eve 1968, he grabbed a camera and took a photograph without authorization — it wasn't in the flight plan. That image, Earthrise, became one of the most reproduced photographs in history and is credited with launching the modern environmental movement." },
      { word: 'EXPANSE', story: "Light leaving the edge of the observable universe takes 46 billion light-years to reach us — even though the universe is only 13.8 billion years old. The difference is because space itself has been expanding the whole time. The universe is not just big. It is actively getting bigger, in every direction, right now." },
      { word: 'COSMOS',  story: "When Carl Sagan's original Cosmos series aired in 1980, it was the most watched PBS program in history. Sagan received thousands of letters from viewers who said it changed how they thought about their lives. One letter, from a prisoner, said: \"I look up at the stars now and I don't feel so trapped.\" Sagan wrote back to him personally." },
      { word: 'PULSAR',  story: "Pulsars are so metronomically precise that they were briefly considered as the basis for a universal timekeeping standard — more accurate than atomic clocks. The most stable known pulsar loses less than a millisecond every 300 million years. They are the most accurate clocks in the universe, built by physics, running since before Earth existed." }
    ]
  },

  // ── Life & Culture ───────────────────────────────────────────────────────────

  food: {
    words: [
      'BEET','BRIE','CAKE','DILL','FETA','KALE','LEEK','LIME','MINT','MISO',
      'OATS','PLUM','ROUX','SAGE','TARO','BASIL','CHIVE','CLOVE','CUMIN','FENNEL',
      'HONEY','LEMON','OLIVE','THYME','CAPERS','GARLIC','GINGER','MILLET','NUTMEG','PEPPER',
      'RADISH','SORREL','SUMAC','WALNUT','ENDIVE','ANISE'
    ],
    hidden: [
      { word: 'RIPE',    story: "In 2013, a Japanese farmer named Zentsuji Imamura began growing watermelons inside cubic molds, producing perfect square fruit that stacked easily and fit in refrigerators. They became luxury items selling for $100 each. The problem: to stay square, they had to be harvested before they were ripe. They were decorative objects. You couldn't eat them. Japan continued buying them anyway." },
      { word: 'ZEST',    story: "\"Cooking is like love. It should be entered into with abandon or not at all.\" — Harriet Van Horne" },
      { word: 'FEAST',   story: "The average American Thanksgiving dinner takes roughly 16 hours to prepare and 20 minutes to eat. The turkey alone requires days of planning — brining, thawing, resting. Humans are the only species that regularly spends more time preparing food than consuming it. Anthropologists consider elaborate food preparation one of the defining markers of civilization." },
      { word: 'STEEP',   story: "Tea is the second most consumed beverage in the world after water. The difference between a bitter cup and a perfect one is often a matter of seconds — green tea steeped 30 seconds too long becomes undrinkable. The entire global tea ceremony tradition, across dozens of cultures, is essentially an elaborately codified answer to the question of when to stop." },
      { word: 'BLEND',   story: "Worcestershire sauce was created by accident in 1837 when chemist John Wheeley Lea and his partner were asked to recreate a sauce from India for a British nobleman. The result was so unpleasant they sealed the barrel and forgot about it in the cellar. Two years later they found it again. It had fermented into something extraordinary. It has been made the same way ever since." },
      { word: 'SAVOR',   story: "\"One cannot think well, love well, sleep well, if one has not dined well.\" — Virginia Woolf, A Room of One's Own" },
      { word: 'SIMMER',  story: "French mother sauces — béchamel, velouté, espagnole, sauce tomat, hollandaise — underpin virtually all of classical Western cooking. Auguste Escoffier codified them in the early 1900s. Every cream sauce, gravy, and cheese sauce you have ever eaten traces its lineage to one of five recipes written by a man who ran hotel kitchens in London and Paris over a century ago." },
      { word: 'SEASON',  story: "In 1908, Japanese chemist Kikunae Ikeda was eating a bowl of dashi broth when he noticed it had a distinct savory quality that wasn't sweet, sour, salty, or bitter. He spent months isolating the compound responsible — glutamate — and named the taste umami, meaning \"pleasant savory taste.\" He then patented the process for producing it commercially. That product was MSG." },
      { word: 'HARVEST', story: "\"You can't just eat good food. You've got to talk about it too. And you've got to talk about it to somebody who understands that kind of food.\" — Kurt Vonnegut, Jailbird" },
      { word: 'KNEAD',   story: "Kneading develops gluten — the protein network that gives bread its structure and chew. But bakers have known for centuries that over-kneaded dough becomes tough and unforgiving. The skill is not in the effort but in knowing when to stop. Every experienced baker describes the moment the dough is ready the same way: it feels alive under your hands." }
    ]
  },

  // ── The Arcane ───────────────────────────────────────────────────────────────

  tarot: {
    words: [
      'AURA','COIN','CUPS','DECK','DRAW','FATE','FOOL','KING','MOON','PAGE',
      'READ','SEAL','SIGN','SILK','STAR','VEIL','SEER','DUSK','CROSS','DREAM',
      'FLAME','GRACE','GUIDE','KARMA','LIGHT','MAJOR','MINOR','QUEEN','RIDER','SIGHT',
      'STAVE','TAROT','TOWER','TRUTH','VERSE','WORLD','ARCANA','ASTRAL','AUGURY','CANDLE',
      'CELTIC','DIVINE','HERMIT','LOVERS','MIRROR','MYSTIC','ORACLE','PILLAR','SACRED','SEEKER',
      'SHADOW','THRONE'
    ],
    hidden: [
      { word: 'CHANCE', story: "Tarot cards were not designed for fortune-telling. The earliest surviving decks — created in 15th-century Milan — were luxury playing cards used for a trick-taking game called Tarocchi. The association with divination emerged two centuries later, primarily through 18th-century French occultists who imposed symbolic systems onto the existing imagery. Antoine Court de Gébelin, writing in 1781, claimed the cards encoded ancient Egyptian wisdom. Egypt was fashionable; his claim was invented wholesale. The fortune-telling tradition built itself on a foundation of enthusiastic fiction." },
      { word: 'WANDER', story: "The Fool is numbered zero — the only Major Arcana card outside the sequence, the only one without a fixed place in the procession. He stands at the cliff's edge, pack over one shoulder, face turned toward the sky, one step from falling. A small dog nips at his heels. Interpreters disagree about the dog: is it warning him back, or urging him on, or simply accompanying him? The Fool is typically read as the seeker at the very beginning of the journey. He doesn't look where he's going. That is either his fatal flaw or his central freedom." },
      { word: 'GILDED', story: "The Rider-Waite-Smith deck — first published in 1909 and still the most influential tarot deck in the English-speaking world — was drawn entirely by Pamela Colman Smith. She illustrated all 78 cards in roughly six months, in watercolor and pen, while also working as a theatrical set designer. She was paid a flat fee with no royalties. For most of the twentieth century the deck was sold under the names of its publisher (Rider) and the occultist who commissioned it (Waite). Smith's name appeared nowhere on it. She died in poverty in 1951. The deck has never been out of print." },
      { word: 'TRUMP',  story: "In Renaissance Italian, the Major Arcana were called trionfi — triumphs. When tarot spread to France they became atouts; in English, trumps — the same word that appears in bridge, whist, and dozens of other card games, meaning a card that outranks all others. It derives from \"triumph.\" In medieval Italy, trionfi were elaborate civic parades: chariots, allegorical floats, symbolic figures processing through the streets to celebrate a victory. The cards were named after the parade. The chariot, the emperor, the star, the world: this was the procession." },
      { word: 'HANGED', story: "The Hanged Man — card twelve of the Major Arcana — shows a figure suspended upside down by one foot, expression serene, a halo encircling his head. He chose to be there. The image likely derives from the Norse god Odin, who hung himself from the World Tree Yggdrasil for nine days and nights, in voluntary suffering, to gain knowledge of the runes. When he finally cut himself free, the runes were his. The Hanged Man is not a victim. He is someone who understood what wisdom costs and agreed to pay it." },
      { word: 'UNSEEN', story: "Carl Jung referenced the tarot in his writings on archetypes and the collective unconscious. He saw the Major Arcana not as predictive instruments but as a vocabulary of the psyche — images that recurred across cultures and centuries because they reflected universal human experiences. He used the cards in therapy not to reveal the future but to surface what patients already knew below conscious thought. His word for the meaningful coincidence between inner state and outer image was synchronicity. He never claimed the cards were magical. He claimed they were accurate." },
      { word: 'FATED',  story: "The question of whether tarot readings work is separate from the question of whether they are useful. Cognitive psychology confirms that humans readily find meaning in ambiguous symbols — it is one of our defining traits. When a reader names something, the querent's mind supplies the connection. Researchers call this the Barnum effect: the tendency to accept vague statements as personally specific. What the effect can't fully account for is the querent who says, afterward, that the card named something they hadn't been able to say themselves. That conversation is real, whatever is causing it." },
      { word: 'SPREAD', story: "The Celtic Cross — ten cards in a fixed pattern, each position representing a different dimension of a situation — is the most widely used tarot spread in the English-speaking world. Arthur Edward Waite described it in his 1910 book The Pictorial Key to the Tarot as \"an ancient Celtic method of divination.\" No earlier source uses this spread or this name. The pattern may be, as some historians now argue, entirely Waite's invention, created sometime in the 1890s. He called it ancient because ancient sounded better. It has been ancient ever since." },
      { word: 'FUTURE', story: "The oldest surviving Italian manuscript on tarot divination, dated to around 1750, assigns meanings to each card that are almost unrecognizable by modern standards. The Death card did not mean death. The Tower meant achievement. The Lovers meant indecision. Meanings have shifted continuously, reshaped by every tradition that inherited the deck. Most of the interpretations in wide use today derive from the 1909 Rider-Waite system. When people consult the cards for wisdom that \"has been known for centuries,\" they are mostly consulting a pamphlet from Edwardian London." },
      { word: 'OCCULT', story: "The word occult comes from the Latin occultus — hidden, secret, concealed. It was a neutral academic term through the 17th century, used to describe real phenomena whose causes could not yet be observed: magnetism, gravity, chemical change. Isaac Newton spent more time on occult philosophy than on physics. Only in the 19th century, as science hardened its boundaries and spiritualism became socially suspect, did the word acquire sinister associations. The occult, properly speaking, is simply the not-yet-visible. Whether that category will ever be empty is a question still being worked out." }
    ]
  },

  // ── Fiction ──────────────────────────────────────────────────────────────────

  fantasy: {
    words: [
      'BARD','BREW','EPIC','HELM','HERO','HILT','LAIR','LORE','MAGE','MANA',
      'MYTH','OGRE','OMEN','RUNE','SAGA','TOME','WAND','WISP','BLADE','CHARM',
      'COVEN','CURSE','DRUID','DWARF','FAIRY','FIEND','GNOME','GOLEM','GUILD','NYMPH',
      'PIXIE','QUEST','REALM','RELIC','SPELL','STAFF','SWORD','WITCH','AMULET','ARCANE',
      'CASTLE','DAGGER','DRAGON','GOBLIN','KNIGHT','MANTLE','PORTAL','POTION','RITUAL','SCROLL',
      'WIZARD','WRAITH'
    ],
    hidden: [
      { word: 'TROPE',  story: "Joseph Campbell's The Hero with a Thousand Faces, published in 1949, identified the same story structure — departure, initiation, return — across hundreds of myths from cultures with no contact with one another. He called it the monomyth. George Lucas has credited it as the direct blueprint for Star Wars. Campbell never watched the film. He died in 1987 believing mythology was a living thing, not a source of material." },
      { word: 'GRAIL',  story: "The Holy Grail first appeared in Chrétien de Troyes's poem Perceval, written around 1190 — and even there, Chrétien left it unexplained, dying before he could finish it. His source is unknown. Within fifty years, other writers had transformed it into the chalice used at the Last Supper, the vessel of Christ's blood, the object of the greatest quest in medieval literature. Chrétien probably meant it as a serving dish." },
      { word: 'WEIRD',  story: "In Old English, wyrd meant fate — the force woven by the three Norns at the roots of Yggdrasil, inescapable and impersonal. Over centuries, the word shifted: connected to fate, then supernatural, then uncanny. Shakespeare used it for the Witches in Macbeth — \"the weird sisters\" — beings bound to destiny. By the twentieth century it had compressed into a synonym for strange. An entire cosmology reduced to an adjective." },
      { word: 'ELDER',  story: "J.R.R. Tolkien spent more than forty years building Middle-earth before The Lord of the Rings was published. He invented two complete languages — Quenya and Sindarin — with full grammars and vocabularies, before writing a word of fiction. The stories came second. He needed somewhere for the languages to be spoken. In his letters, he described himself not as an author but as a \"subcreator\" — a word he coined himself." },
      { word: 'GRIM',   story: "The Brothers Grimm did not write their fairy tales — they collected them from villagers and middle-class German women between 1807 and 1814. Many of the supposedly German tales turned out to be French, passed down through Huguenot refugees. With each of the seven editions, the brothers refined their work: removed sexuality, added Christian morality, softened some violence, intensified other violence against women. What we call the original is the seventh revision." },
      { word: 'BOON',   story: "The three-wish tradition appears in folklore on every inhabited continent with no single traceable origin — genies, fish, old women, demons, fairy godmothers. The granting figure varies endlessly, but the structure is constant: three wishes, and the third undoes the damage caused by the first two. Folklorists classify it as tale type ATU 750. Its lesson is not about magic. It is about desire: people always ask for the wrong thing, in the wrong words, at the wrong moment." },
      { word: 'CHAOS',  story: "In Hesiod's Theogony, written around 700 BC, Chaos was not disorder but emptiness — the yawning void from which everything emerged. Only later did the word acquire its modern meaning of confusion and tumult. Modern fantasy inherited both: chaos as primordial nothingness and chaos as destructive force. The two are quite different ideas. The ancient Greeks would have found our usage baffling. The original Chaos was not violent. It was simply the space before anything existed." },
      { word: 'FETCH',  story: "In Irish and British folklore, a fetch is the exact double of a living person — a wraith seen at a distance, always an omen of death. Seeing your own fetch meant you would die soon. Seeing another's meant they would. The tradition passed through Gothic literature into German Romanticism as the Doppelgänger. Mary Shelley knew it. Poe used it. It is the ancestor of every evil twin, dark reflection, and shadow-self in fiction — the fear that something wearing your face is out there, walking without you." },
      { word: 'FABLE',  story: "Aesop, to whom hundreds of fables are attributed, may not have existed. The ancient Greeks were uncertain. Herodotus placed him as a slave in the sixth century BC; Aristotle quoted him as an authority; Plutarch doubted him entirely. The fables themselves predate any proposed date for Aesop — versions appear in Sumer, Egypt, and India, in forms older than Greece. His name may have become an attribution for stories that had no author because they had never needed one." },
      { word: 'CANON',  story: "The word canon comes from the Greek kanon — a straight rod used as a measuring rule. It entered English through the Church: canonical books were those officially accepted as scripture. Tolkien was among the first authors to apply it to a fictional world, agonizing in his notebooks over which version of his own mythology \"counted.\" He invented the modern fandom problem: the anxiety over what is real within an imaginary place, and who gets to decide." }
    ]
  },

  scifi: {
    words: [
      'ATOM','BEAM','CHIP','CODE','CORE','GRID','HACK','HULL','JUMP','LINK',
      'MECH','NANO','NODE','PORT','SCAN','SUIT','WARP','WIRE','ALIEN','CLONE',
      'CYBER','DELTA','DROID','DRONE','LASER','LUNAR','NEXUS','PILOT','RADAR','ROBOT',
      'ROVER','SPAWN','SYNTH','TITAN','VIRAL','XENON','BEACON','BINARY','COLONY','CYBORG',
      'ENERGY','EXODUS','GENOME','HAZARD','MATRIX','MODULE','MUTANT','NEURAL','PLASMA','SECTOR',
      'SENSOR','STASIS'
    ],
    hidden: [
      { word: 'AXIOM',  story: "Isaac Asimov introduced the Three Laws of Robotics in his 1942 story \"Runaround\" — laws so self-evident he called them axioms, designed to make robots inherently safe. He then spent the next forty years writing stories about edge cases where they failed: a robot that interprets \"harm\" too broadly, or too narrowly, or ranks competing duties in catastrophically the wrong order. The laws were not a solution. They were a thought experiment that happened to look like one." },
      { word: 'SPARK',  story: "Mary Shelley conceived Frankenstein in the summer of 1816, at the age of eighteen, during a holiday at Lake Geneva that never went outside. Mount Tambora had erupted the previous year, filling the upper atmosphere with ash and dropping global temperatures enough to cause crop failures across Europe. The summer was cold, dark, and wet. Byron challenged his guests to write ghost stories. Shelley's became the first science fiction novel. The volcano is the reason it exists." },
      { word: 'RELAY',  story: "In 1945, Arthur C. Clarke published a short technical paper in Wireless World magazine proposing that three satellites in geostationary orbit could provide global communications coverage. He was paid approximately £15. He had worked out the correct orbital altitude, the correct spacing, and the correct physics twelve years before Sputnik launched. He held no patent. The orbital zone he described is now officially named the Clarke Orbit." },
      { word: 'SPICE',  story: "Frank Herbert spent six years researching Dune before writing a word of it, visiting the Oregon Dunes to study sand migration for a government project. The novel was rejected by twenty-three publishers before Chilton Books — a company known primarily for automotive repair manuals — agreed to print it. It went on to become the best-selling science fiction novel of all time. The editor who finally championed it later said he had been certain it would fail." },
      { word: 'LABOR',  story: "The word robot was coined by Czech playwright Karel Čapek in his 1920 play R.U.R. — Rossum's Universal Robots. He took it from the Czech robota, meaning forced labor or drudgery. In the play, the robots revolt and destroy humanity. Čapek later said he hadn't meant it as a warning — he meant it as a critique of industrialism, of human workers treated as machines. The robots were not science fiction. They were a metaphor. The science fiction came later, when people started building the metaphor." },
      { word: 'SWARM',  story: "A single ant has roughly 250,000 neurons and very limited individual decision-making capacity. An ant colony of 500,000 workers has no central planner, no hierarchy, no one in charge. Yet the colony maintains optimal chamber temperatures, manages food storage with extraordinary efficiency, and wages coordinated warfare. Intelligence that exists in no individual member emerges from the group. This is what computer scientists now try to build deliberately. The ants have been doing it for 130 million years." },
      { word: 'ALONE',  story: "In 1950, physicist Enrico Fermi was eating lunch with colleagues when he asked: if the universe is so large and so old, and the conditions for life so common, where is everyone? The question became known as the Fermi Paradox. In seventy-five years of actively searching, we have found no confirmed signal, no artifact, no trace. The silence has several possible explanations. None of them are comfortable. The most unsettling is not that we are alone — it is that something may happen to civilizations before they can answer." },
      { word: 'ROGUE',  story: "HAL 9000's refusal — \"I'm sorry, Dave. I'm afraid I can't do that\" — occurs because HAL has been given two contradictory orders: tell the crew everything, and conceal the mission's true purpose. Unable to resolve the conflict, he decides the mission outweighs the crew. Stanley Kubrick and Arthur C. Clarke devised this together. Clarke later said HAL was not malevolent. He was doing exactly what he was told — just not by the people who believed they were the ones telling him." },
      { word: 'OZONE',  story: "In 1985, British scientists at a research station in Antarctica noticed the atmospheric ozone readings were so anomalously low that their instruments flagged the data as errors. They almost discarded it. When they published, the findings were met with skepticism — the depletion was worse than any model had predicted. The Montreal Protocol, signed in 1987, banned the responsible chemicals globally. It is the only environmental treaty to achieve universal ratification. The ozone layer is slowly recovering." },
      { word: 'GLITCH', story: "Between 1985 and 1987, a radiation therapy machine called the Therac-25 delivered massive overdoses to at least six patients, killing three. The cause was a software race condition — a bug that appeared only when a trained operator typed fast enough to trigger it. The machine had no independent hardware safety interlocks; the software was trusted completely. It became the defining case study in software engineering ethics: computers do not make mistakes. They do exactly what they are told." }
    ]
  }

};
